version: '3'
services:
  express-ts:
    # image: neliocaa/express-ts:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000

    ports:
      - "3001:3000"
